spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5131
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: NEVER
#  sql:
#    init:
#      data-locations: classpath:person.sql

---

spring:
  config:
    activate:
      on-profile: test
    jpa:
      database: h2

---
